# Generated by Django 3.0.7 on 2020-06-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feria',
            fields=[
                ('id_feria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_feria', models.CharField(max_length=150)),
                ('comuna_feria', models.CharField(max_length=150)),
                ('inicio_feria', models.CharField(max_length=200)),
                ('fin_feria', models.CharField(max_length=200)),
                ('horario_ini_feria', models.CharField(max_length=200)),
                ('horario_fin_feria', models.CharField(max_length=200)),
                ('dias_feria', models.CharField(max_length=200)),
                ('imagen_feria', models.ImageField(null=True, upload_to='gallery')),
            ],
        ),
    ]
