# Generated by Django 3.0.7 on 2020-06-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feria',
            name='imagen_feria',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
