# Generated by Django 3.0.7 on 2020-06-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0002_auto_20200629_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feria',
            name='imagen_feria',
        ),
    ]
