# Generated by Django 3.0.8 on 2020-07-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0003_remove_feria_imagen_feria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feria',
            name='horario_fin_feria',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='feria',
            name='horario_ini_feria',
            field=models.TimeField(),
        ),
    ]
