# Generated by Django 3.0.8 on 2020-07-04 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ferias', '0002_auto_20200704_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('feriante', models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('nombre_producto', models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)])),
                ('precio_producto', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)])),
                ('descripcion_producto', models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.MinLengthValidator(5)])),
                ('feria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ferias.Feria')),
            ],
        ),
    ]
