# Generated by Django 3.0.7 on 2020-06-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_producto',
        ),
    ]
