# Generated by Django 3.0.8 on 2020-07-04 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20200702_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(4)]),
        ),
    ]
