# Generated by Django 3.0.8 on 2020-07-04 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20200704_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion_producto',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.MinLengthValidator(5)]),
        ),
    ]
